baseurl: 'https://kassouar.com'
title: Omar Kassouar
languageCode: en-us
defaultContentLanguage: en
enableRobotsTXT: true
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true
disableKinds:
  - RSS
params:
  logo: fa-fingerprint
  shortDescriptions:
    - Passionate autodidact with a soft spot for developer experience, CI/CD, and privacy-by-design.
    - On a mission to further hone my craft while delivering optimal software that real humans actually enjoy using.
  longDescriptions:
    - >-
      Passionate autodidact in the San Francisco Bay Area with a soft spot for developer experience, CI/CD, and privacy-by-design.
    - >-
      My core values are craftsmanship, mentorship, creativity, and user-empathy. On a mission to further hone my craft while delivering optimal software that real humans actually enjoy using. Over a decade of experience building systems that allow products to scale while continuously growing business value. Also interested in learning more about Augmented/Mixed Reality and LLMs. 
  social:
    - medium: linkedin
      icon: "brand fab fa-linkedin"
      link: 'https://linkedin.com/in/okasso'
    - medium: github
      icon: "brand fab fa-github"
      link: 'https://github.com/O-kasso'
    - medium: email
      icon: "far fa-envelope"
      link: 'mailto:omar+websitecontact@kassouar.com'
  work:
    - company: Snap Inc
      position: Software Engineer, Developer Productivity
      logo: /images/logo-snapchat.png
      link: 'https://www.snap.com/'
      time: May 2019 - Jan 2024
      description: Developer Productivity + Mobile Release
      descriptionList: 
        - Designed and developed Golang/gRPC Mobile Release orchestration platform for Snap’s various iOS and Android products that organizes post-merge builds; manages pre-release checks for distribution to internal testing, external beta, and production submission release tracks; monitors and controls production staged rollouts based on internal metric funnels, and maintains fault-tolerant event schedules for different weekly-release milestones.
        - Led effort to modernize and consolidate build scripting across Snap, migrating from bash scripts and deprecated Python2 to modern custom Python3 framework with metrics logging, dynamic error reporting, and modularity/composability.
        - Collaborated with Builds team on redesigning mobile variant system for assembling custom build types and feature sets for different audiences, build graph optimizations and aggressive dependency caching to dramatically reduce compile times for both developer and CI machines. and aggressive dependency caching to dramatically reduce compile times for both developer and CI machines. Coordinated and performed iterative SDK upgrade rollouts and OS deprecations, aligning requirements across feature and ops teams.
        - Owned mobile codesigning, managing storage and rotations of certificates, private keys, provisioning profiles, app IDs, and entitlements across several developer accounts. Refactored codesign build tooling to reduce risk and downtime of rotations. Collaborated with Security teams to maintain functionality of code obfuscation, binary integrity, and client attestation.
        - Participated in Mobile Release Manager on-call rotation, performing production app submissions and hot fixes, managing policy changes and rejections, communicating with Apple / Google reps on behalf of Snap, and aggregating user-facing feature rollout plans for cross-team launch initiatives
    - company: Connected
      position: Software Developer, Automation
      logo: /images/logo-connected-io.png
      link: 'https://www.connected.io/'
      time: Oct 2017 - Present
      description: Design, build, and maintain automated tooling (testing, deployment, utilities) as part of cross-project Integrity initiative serving multiple internal development teams.
      descriptionList:
        - iOS + Android automation framework for running end-to-end smoke tests on physical-devices (Ruby/Appium).
        - Alexa-skill utterance validation framework for comparing NLP results between regional accents (NodeJS/Golang).
        - ML-dataset preprocessing/assignment pipeline (PHP) and asset upload pipeline (Python).
        - IT inventory management app (Swift/NodeJS).
        - Coach traditionally waterfall teams to follow CI/CD best practices.
        - Onboard and mentor co-op students with focus on maximizing their impact.
    - company: Shopify
      position: Software Developer Intern
      logo: /images/logo-shopify.png
      link: 'https://www.shopify.ca/'
      time: Sep 2016 - Dec 2016
      description: Full-stack development on Shipping team; implemented new features and bug fixes within admin settings UI; refactored and expanded coverage of unit and integration tests for Shipping microservice.
    - company: VarageSale
      position: QA Analyst
      logo: /images/logo-varagesale.png
      link: 'https://www.varagesale.com/'
      time: Jun 2014 - Aug 2016
      description: QA on Infrastructure Team, focused on Payments and Notifications systems; automated repetitive tasks and maintained staging deployment bot; verified user stories and defects across web, iOS, and Android; designed test cases for constantly iterating product; collaborated with stakeholders to identify concerns early in dev cycle.
    - company: VMC Game Labs
      position: Compliance Test Specialist (TRC)
      logo: /images/logo-vmc-game-labs.png
      link: 'https://www.vmc.com/games/'
      time: Sep 2011 - Jul 2013
      description: Verified client products against Sony's Technical Requirements Checklist in preperation for PlayStation QAAP submissions; consulted with client teams throughout dev cycle for early-detection and avoidance of potential violations; maintained complex test suites across multiple projects; participated in Sony's DevNet forum and VMC's internal TRC Hotline; on-site contracts for local clients.
  skill:
    - name: Ruby
      icon: devicon-ruby-plain colored
    - name: NodeJS
      icon: devicon-nodejs-plain colored
    - name: Golang
      icon: devicon-go-plain
    - name: Python
      icon: devicon-python-plain colored
    - name: PHP
      icon: devicon-php-plain colored
    - name: Swift
      icon: devicon-swift-plain colored
    - name: SQL
      icon: devicon-postgresql-plain colored
    - name: Unix/Linux
      icon: devicon-linux-plain
    - name: Git
      icon: devicon-git-plain colored
    - name: Shell
      icon: devicon-vim-plain colored
  school:
    - name: nand2tetris
      course: Build a Modern Computer from First Principles
      year: '2017'
      link: 'https://www.coursera.org/learn/build-a-computer'
      logo: /images/logo-coursera.png
    - name: edX Harvard
      course: Computer Science CS50x
      year: '2015'
      link: >-
        https://www.edx.org/course/cs50s-introduction-computer-science-harvardx-cs50x
      logo: /images/logo-cs50x.png
    - name: Vanier College
      course: Computer Science & Mathematics
      year: '2010'
      link: 'http://www.vaniercollege.qc.ca/csm/'
      logo: /images/logo-vanier.jpg
languages:
  en:
    languageName: English

